### ISSUE TITLE
[WIP-FEATURE] - Run Autojob against multiple backend (JDBC / BQ / Parquet)

### ISSUE THREAD

**Issue by hayssams** [ebiznext/comet-data-pipeline#136]
## Description
Currently an auto job executes SQL requests against tables backed by a parquet storage.
This feature intend to add tables backed by other storages including JDBC & BQ.
## Additional context
This could include:
- Design diagrams
- Documentation draft
- Migration strategy
- Adoption and teachability for this feature

# Life cycle

## Possible implementation
Describe here a brief for any contributor wishing to work on this issue

## Complexity estimation
T-Shirt Size: XS, S, M, L. If you would recommend XL or more, we advise you to discuss with the community how to split this issue.
Don't forget to tag this issue as a 'good first issue' if you think it is appropriate!

**Comment by cchepelov** [comment]
We could have a `CompositeSink` that takes a list of sinks, and passes the data on to each successively.

One question: what if one of the sub-sinks fails; should we fail all? should we fail one? Should the ingestion itself be considered failed and to be redone? What then, if the first non-failed sub-sink is not idempotent, how do we deal with duplicates while we re-attempt the failed sub-sinks and the non-tried sub-sinks? 

Another option would be to *refuse* to have `CompositeSink` and instead decide the way to go is to have a single `MessageQueueSink`(e.g. `KafkaSink`, `PulsarSink`, whatever) and then as many MQSource→IndexSink consumers. 

Whichever side the coin lands, perhaps we should write an ADR for this?

**Comment by mhdkassir** [comment]
My understanding of the description of this feature is that _autojobs_ should be able to query data in formats/storage different than parquet files, but @cchepelov question seems to be rather about how to store the result of an _autojob_ in different sinks. @hayssams , the feature concerns the the input data of an _autojob_ or its result storage ?

**Comment by hayssams** [comment]
@mhdkassir @cchepelov 
The composite sink is interesting as a starter.
Actually we need to have a generic reader and writer to support the following flow 
Reader -> Autojob  -> Writer where readers & writers are able to respectively read and writer parquet / jdbc/ BQ sources & sinks.
I will draft a simple solution and share it soon  to get your feedbacks.

**Comment by cchepelov** [comment]
I like this

Yes, the `parquet write -> foreach(sink) { parquet read -> deliver }` route seems quite promising in order to keep things simple on the requirements side. I'm a bit less sure we should try to daisy-chain sinks (i.e. *Comet* writes to sink1, then pulls from sink1 to write to sink2, then pulls from sink2 to write to sink3 — did I misread?)

There is a very fine balancing act to do here to avoid reimplementing Kafka as an HDFS-based queue protocol. I'd suggest:
  * making this a pluggable module, where the default implementation is indeed batch-oriented and uses the pq->*->pq->sink route with zero dependencies, but one could swap in a full MQ-based dispatcher implementation (Kafka, Pulsar, SQS, AQS,... if you name it, patches welcome). Joke aside, this pluggability will enable one to work with different guarantee/complexity balances that the simple and "works decently out of the box" defaults we ought to provide.
  * making reasonable steps towards reliability×performance but draw a line beyond which swapping out the default module and providing additional infrastructure *is* the way to go

to clarify the second point, I think:
- we should support recovering from one sink failing after another sink succeeded
- we might want to try supporting one sink running _multiple_ delivery batches ahead of a failing sink
- we might want to try supporting some avoidance of duplication in case we can't guarantee a sink's output batch is either delivered entirely or not at all (e.g. a failure happens mid-delivery), but as soon as that becomes too complicated to support, we should push people towards using a reliable delivery-based infrastructure 
- to support the previous point, we *might* want to have a different granularity between the working parquet output and the sink output (e.g. we may want to output single well-sized transactions on the JDBC sink side, irrespective of how many records are sitting within each parquet file in the working area)... But here comes the "mature queue system envy".

**Comment by hayssams** [comment]
Done
